### ISSUE TITLE
[Multiprocess/electrolysis addon] Error with refreshing the speed indicator / information not found video

### ISSUE THREAD

**Issue by ghost** [fx4waldi/playbackSpeed#1]
Windows **10 x86**, **1709** FCU; Firefox **58b8** (problem był też w stabilnej wersji **57**).

Na stronie z wideo klikamy w `1.5`, klikamy `2` i mamy `2 5`:

![obraz](https://user-images.githubusercontent.com/33114475/33580371-3c51c632-d94d-11e7-89cb-90a2dbc45b3d.png)

**Comment by WaldiPL** [comment]
Nie mogę odtworzyć tego błędu. Czy problem występuje na każdej stronie, czy tylko na niektórych?

**Comment by ghost** [comment]
Na każdej np. [www.quirksmode.org/html5/tests/video.html](https://www.quirksmode.org/html5/tests/video.html), [www.w3schools.com/html/html5_video.asp](https://www.w3schools.com/html/html5_video.asp)

Sprawdzę jeszcze bez projektu `CustomCSSforFx` - też mam, nie potrafi wymazać tej starej cyfry i kropki.


---

`browser.tabs.remote.force-disable` - `Okna wieloprocesowe:	0/1 (wymuszone wyłączenie)` i zaczęło dobrze odświeżać cyfrę i kropkę.

**Comment by WaldiPL** [comment]
Problem spowodowany jest nieprawidłowym renderowaniem i występuje tylko jeśli opcja `extensions.webextensions.remote` ma wartość `true`. Dodanie białego tła usuwa ten problem. Wkrótce dodam nową wersję.

**Comment by ghost** [comment]
@WaldiPL  Teraz mam na początku jakieś e

![obraz](https://user-images.githubusercontent.com/33114475/33777932-fbb744d8-dc46-11e7-9127-9e1ea2130250.png)

**Comment by WaldiPL** [comment]
`e` pochodzi z `Brak filmów na tej stronie`.
Wieczorem prześlę nową wersję, która usunie wszystkie tego typu problemy.

**Comment by ghost** [comment]
I działa świetnie :)
