### ISSUE TITLE
Default keyboard shortcut conflicts

### ISSUE THREAD

**Issue by grahamperrin** [fx4waldi/playbackSpeed#15]
![shortcuts](https://user-images.githubusercontent.com/192271/67259806-ad822900-f48f-11e9-852a-e817709d0b5d.png)

<kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>Left</kbd> and <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>Right</kbd> are commonly used for selection (e.g. in the address bar). 

Can you find alternatives? Thanks. 

Unfortunately Firefox does not allow a shortcut to be un-set so in cases such as this, I tend to simply disable the conflicting extension. Easier than forcing me to think of alternatives. (No offence; I'm just being realistic.)

**Comment by Zegnat** [comment]
<kbd>alt</kbd>+<kbd>shift</kbd> is what I use for selection in the address bar on macOS, which is being stopped by this addon right now. It is very frustrating for sure. A [fix should be upcoming for Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1520119) but has not landed yet, so a different default (or no default at all) would be preferable right now.

@WaldiPL would you consider accepting a PR for this, or am I better off forking the entire extension?

**Comment by grahamperrin** [comment]
I disabled the extension. Firefox 74 will include a fix.

**Comment by grahamperrin** [comment]
PS if my previous comment seemed petulant: sorry! It wasn't. I'm grateful for the extension. 

Disabling it was simply a quick workaround for me personally, i.e. not to put pressure on @WaldiPL 

Thanks again

**Comment by WaldiPL** [comment]
In version 1.4.2 it is possible to delete keyboard shortcuts.
