### ISSUE TITLE
Resets settings after player interaction

### ISSUE THREAD

**Issue by deniss-s** [fx4waldi/playbackSpeed#16]
1. Open a video and set the speed.
2. When watching the video at custom speed click pause or fast forward the video.
3. Video speed is reset to default, but the icon still shows custom presets.

**Comment by deniss-s** [comment]
Noticed this behavior only with player used on TED talks (https://www.ted.com/talks).

**Comment by WaldiPL** [comment]
The script at ted.com resets the playback speed. In version 1.4.2, on the icon, is displayed the current speed.

**Comment by krystian3w** [comment]
Similar reset generate "end screen propositions" on YouTube.
