### ISSUE TITLE
Scroll bar not visible in preferences

### ISSUE THREAD

**Issue by grahamperrin** [fx4waldi/playbackSpeed#17]
![2020-03-09 22:20:42](https://user-images.githubusercontent.com/192271/76262718-04c54200-6255-11ea-924c-efed3cb505c8.png)

`extensions.htmlaboutaddons.inline-options.enabled` is `false`

**Comment by WaldiPL** [comment]
This bug has now been fixed.

**Comment by grahamperrin** [comment]
Fix confirmed. Thanks!
