### ISSUE TITLE
[Audio] speed audio tag

### ISSUE THREAD

**Issue by ghost** [fx4waldi/playbackSpeed#2]
Zastanawiało mnie czy dałoby się może rozszerzyć działanie o tag `<audio>`, teoretycznie w nowej karcie firefox dla plików audio wrzuca je w tag `<video>` i można przyśpieszyć wolną muzykę.

**Comment by WaldiPL** [comment]
W nowej wersji będzie to dostępne.

**Comment by ghost** [comment]
Działa na https://hpr.dogphilosophy.net/test/, działa też z częścią serwisów audio jeśli nie przekombinowali z odtwarzaczem.

@WaldiPL  przy 0.3 / 0.4 też nie słyszysz audio? Chrome z YouTube tak nie miał (zwalnianie z zębatki).

**Comment by Sexylilmama91** [comment]
> Działa na https://hpr.dogphilosophy.net/test/, działa też z częścią serwisów audio jeśli nie przekombinowali z odtwarzaczem.
> 
> @WaldiPL przy 0.3 / 0.4 też nie słyszysz audio? Chrome z YouTube tak nie miał (zwalnianie z zębatki).
