### ISSUE TITLE
Not seeing embedded videos

### ISSUE THREAD

**Issue by MarieDi** [fx4waldi/playbackSpeed#5]
This used to work perfectly.
After update to FF 58 on MacBookPro OS 10.10.5, it doesn't see any embedded video on pages.

For instance: someone embedded a YouTube or Vimeo video on their page? The response from the add-on is that there is no video on the page. If you go to YouTube directly or open the video alone in it's own page/tab, the add-on sees it and you can adjust the speed.

So basically, it has become completely useless and will remain so until it can see the videos embedded in a page.

I'm so very disappointed with loosing functionality with so many add-ons with Quantum, it's not even funny. :-(

**Comment by WaldiPL** [comment]
The extension in version 1.4.2 works with embedded video.
