### ISSUE TITLE
Icon is too similar to "More tools..." toolbar button

### ISSUE THREAD

**Issue by TheIronBorn** [fx4waldi/playbackSpeed#8]
see: ![screen shot 2018-09-08 at 20 18 58](https://user-images.githubusercontent.com/7707250/45260773-5a5e2b80-b3df-11e8-8f04-2c66d6c41bdf.png)

Something like a double filled arrow rather than chevrons might be better.

**Comment by krystian3w** [comment]
I see still old icon?

![obraz](https://user-images.githubusercontent.com/35370833/61662838-8e78cd00-accf-11e9-8d09-fedcf19458b8.png)  |
--- |

Need remove "Startup Cache" or reboot browser?

https://github.com/Aris-t2/CustomJSforFx#scriptstartup-cache-must-be-deleted-after-every-change

**Comment by WaldiPL** [comment]
The icon should change after the browser restart.
