### ISSUE TITLE
Lost layout settings in v1.4.0

### ISSUE THREAD

**Issue by krystian3w** [fx4waldi/playbackSpeed#9]
To normalne jak sobie wymuszę ponowną instalacje to traci się układ i wraca do domyślnego?

Nie zacznie się on resetować jak zostanie wydana poprawka a to nie wyłapane czemu się nie zapisuje?

**Comment by WaldiPL** [comment]
Dzięki za zgłoszenie. Ten błąd zostanie usunięty w kolejnej aktualizacji.
